-- tag::schema[]
create table if not exists deck (
    id      bigint generated by default as identity primary key,
    name    varchar(100) not null,
    deleted boolean      not null default false
);

create table if not exists card (
    id      bigint generated by default as identity primary key,
    deck_id bigint       not null references deck (id),
    text    varchar(500) not null,
    meaning varchar(500) not null
);

create table if not exists card_example (
    id            bigint generated by default as identity primary key,
    card_id       bigint       not null references card (id) on delete cascade,
    example_index int          not null,
    sentence      varchar(500) not null,
    translation   varchar(500) not null
);

create index if not exists card_deck_idx on card (deck_id);
-- end::schema[]
