-- tag::schema[]
create table if not exists deck (
    id                         bigint generated by default as identity primary key,
    name                       varchar(100) not null,
    policy_new_cards_per_day   int          not null,
    policy_max_reviews_per_day int          not null,
    created_at                 timestamp    not null,
    updated_at                 timestamp    not null
);

create table if not exists card (
    id         bigint generated by default as identity primary key,
    deck_id    bigint        not null references deck (id) on delete cascade,
    text       varchar(500)  not null,
    meaning    varchar(500)  not null,
    tags       varchar(1000) not null,
    created_at timestamp     not null,
    updated_at timestamp     not null
);

create index if not exists card_deck_idx on card (deck_id);
-- end::schema[]
