-- tag::schema[]
create table if not exists deck (
    id         bigint generated by default as identity primary key,
    name       varchar(100) not null,
    created_at timestamp    not null
);

create table if not exists card (
    id         bigint generated by default as identity primary key,
    deck_id    bigint       not null references deck (id) on delete cascade,
    text       varchar(500) not null,
    meaning    varchar(500) not null,
    created_at timestamp    not null
);

create index if not exists card_deck_idx on card (deck_id);

create table if not exists tag (
    id   bigint generated by default as identity primary key,
    name varchar(50) not null unique
);

create table if not exists card_tag (
    card_id bigint not null references card (id) on delete cascade,
    tag_id  bigint not null references tag (id) on delete cascade,
    primary key (card_id, tag_id)
);

-- 카드마다 하나씩: 다음 복습 일정과 누적 성적
create table if not exists review_state (
    id               bigint generated by default as identity primary key,
    card_id          bigint not null unique references card (id) on delete cascade,
    interval_days    int    not null default 0,
    due_date         date,
    correct_count    int    not null default 0,
    wrong_count      int    not null default 0,
    last_reviewed_at timestamp
);

create index if not exists review_state_due_idx on review_state (due_date);

-- 판정 한 번마다 한 행: 통계의 원천 데이터
create table if not exists review_log (
    id          bigint generated by default as identity primary key,
    card_id     bigint    not null references card (id) on delete cascade,
    correct     boolean   not null,
    retry_round boolean   not null,
    reviewed_at timestamp not null,
    study_date  date      not null
);

create index if not exists review_log_date_idx on review_log (study_date);

create table if not exists smart_deck (
    id             bigint generated by default as identity primary key,
    name           varchar(100) not null,
    condition_type varchar(20)  not null,
    param          varchar(100)
);
-- end::schema[]
