package flashcard.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * JDBC의 핵심 인터페이스를 한 바퀴 도는 실행 예제.
 * 실행: ./gradlew :ch01-jdbc-basics:run
 */
public class JdbcQuickTour {

    // tag::url[]
    static final String URL = "jdbc:h2:./db/flashcard;AUTO_SERVER=TRUE";
    // end::url[]

    public static void main(String[] args) throws SQLException {
        // tag::driver-manager[]
        try (Connection connection = DriverManager.getConnection(URL, "sa", "")) {
            System.out.println("연결한 DB: " + connection.getMetaData().getDatabaseProductName());
            System.out.println("JDBC 드라이버: " + connection.getMetaData().getDriverName());
            // end::driver-manager[]

            createTables(connection);
            long deckId = insertDeck(connection, "영어 단어장");
            insertCard(connection, deckId, "resilient", "회복력 있는");
            insertCard(connection, deckId, "deliberate", "의도적인, 신중한");
            printCards(connection, deckId);
        }
    }

    // tag::statement-ddl[]
    static void createTables(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                    create table if not exists decks (
                        id   bigint generated by default as identity primary key,
                        name varchar(100) not null
                    )""");
            statement.execute("""
                    create table if not exists cards (
                        id      bigint generated by default as identity primary key,
                        deck_id bigint       not null references decks (id) on delete cascade,
                        text    varchar(500) not null,
                        meaning varchar(500) not null
                    )""");
        }
    }
    // end::statement-ddl[]

    // tag::insert[]
    static long insertDeck(Connection connection, String name) throws SQLException {
        String sql = "insert into decks (name) values (?)";
        try (PreparedStatement statement =
                     connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, name);
            int inserted = statement.executeUpdate();
            System.out.println("추가된 덱 수: " + inserted);

            try (ResultSet keys = statement.getGeneratedKeys()) {
                keys.next();
                return keys.getLong(1);
            }
        }
    }
    // end::insert[]

    static void insertCard(Connection connection, long deckId, String text, String meaning)
            throws SQLException {
        String sql = "insert into cards (deck_id, text, meaning) values (?, ?, ?)";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setLong(1, deckId);
            statement.setString(2, text);
            statement.setString(3, meaning);
            statement.executeUpdate();
        }
    }

    // tag::select[]
    static void printCards(Connection connection, long deckId) throws SQLException {
        String sql = "select id, text, meaning from cards where deck_id = ? order by id";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setLong(1, deckId);

            try (ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    System.out.printf("%d. %s : %s%n",
                            resultSet.getLong("id"),
                            resultSet.getString("text"),
                            resultSet.getString("meaning"));
                }
            }
        }
    }
    // end::select[]
}
