-- tag::schema[]
create table if not exists decks (
    id      bigint generated by default as identity primary key,
    name    varchar(100) not null,
    version bigint       not null default 0
);

create table if not exists cards (
    id         bigint generated by default as identity primary key,
    deck_id    bigint       not null references decks (id) on delete cascade,
    card_index int          not null,
    text       varchar(500) not null,
    meaning    varchar(500) not null
);

create index if not exists cards_deck_idx on cards (deck_id);
-- end::schema[]
