-- tag::schema[]
create table if not exists decks (
    id   bigint generated by default as identity primary key,
    name varchar(100) not null,
    constraint uq_deck_name unique (name)
);

create table if not exists cards (
    id      bigint generated by default as identity primary key,
    deck_id bigint       not null references decks (id) on delete cascade,
    text    varchar(500) not null,
    meaning varchar(500) not null
);

create index if not exists cards_deck_idx on cards (deck_id);
-- end::schema[]
